### ISSUE TITLE
Could we update this so that required coverage level is an input option?

### ISSUE THREAD

**Issue by andyb3** [moka-guys/dnanexus_sambamba_chanjo#22]
Currently app is hardcoded to calculate percentage coverage at 30x unless Pan493 is found in filename in which case it uses 20x. However some older WES files requiring reanalysis don't have Pan493 in filename, and focussed exome panels also require coverage at 20x.

Maybe change it so that any coverage level can be specified as an input?

**Comment by aledj2** [comment]
done in release 1.8
